/*
 * Copyright (c) 2026 Contributors to the Eclipse Foundation.
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 */

/**
 * Generated by scripts/sync-ecore.mjs from model-sources.json - do not edit.
 *
 * Topological: every model appears after the ones it references. An `optional`
 * model is left out unless asked for; today that is only `engine`, 868 KB whose
 * absence costs exactly 18 features, all on DDL commands a client never sends.
 */
export interface ModelDescriptor {
  readonly name: string;
  readonly nsURI: string;
  readonly optional: boolean;
}

export const MODEL_ORDER: readonly ModelDescriptor[] = [
  { name: "an", nsURI: "http://schemas.microsoft.com/ado/2009/02/edm/annotation", optional: false },
  { name: "bi", nsURI: "http://schemas.microsoft.com/sqlbi/2010/10/edm/extensions", optional: false },
  { name: "cg", nsURI: "http://schemas.microsoft.com/ado/2006/04/codegeneration", optional: false },
  { name: "edm", nsURI: "http://schemas.microsoft.com/ado/2008/09/edm", optional: false },
  { name: "empty", nsURI: "urn:schemas-microsoft-com:xml-analysis:empty", optional: false },
  { name: "engine300", nsURI: "http://schemas.microsoft.com/analysisservices/2011/engine/300", optional: false },
  { name: "engine300_300", nsURI: "http://schemas.microsoft.com/analysisservices/2011/engine/300/300", optional: false },
  { name: "engine", nsURI: "http://schemas.microsoft.com/analysisservices/2003/engine", optional: true },
  { name: "engine200", nsURI: "http://schemas.microsoft.com/analysisservices/2010/engine/200", optional: false },
  { name: "engine200_200", nsURI: "http://schemas.microsoft.com/analysisservices/2010/engine/200/200", optional: false },
  { name: "exception", nsURI: "urn:schemas-microsoft-com:xml-analysis:exception", optional: false },
  { name: "ext", nsURI: "http://schemas.microsoft.com/analysisservices/2003/ext", optional: false },
  { name: "mddataset", nsURI: "urn:schemas-microsoft-com:xml-analysis:mddataset", optional: false },
  { name: "msxmla", nsURI: "http://schemas.microsoft.com/analysisservices/2003/xmla", optional: false },
  { name: "multipleresults", nsURI: "http://schemas.microsoft.com/analysisservices/2003/xmla-multipleresults", optional: false },
  { name: "rowset-core", nsURI: "urn:schemas-microsoft-com:xml-analysis:rowset:core", optional: false },
  { name: "rowset-core-restrictions", nsURI: "https://www.daanse.org/spec/xmla/rowset/core/restrictions/1.0", optional: false },
  { name: "rowset-relational-restrictions", nsURI: "https://www.daanse.org/spec/xmla/rowset/relational/restrictions/1.0", optional: false },
  { name: "rowset-relational", nsURI: "urn:schemas-microsoft-com:xml-analysis:rowset:relational", optional: false },
  { name: "rowset-multidimensional-restrictions", nsURI: "https://www.daanse.org/spec/xmla/rowset/multidimensional/restrictions/1.0", optional: false },
  { name: "rowset-multidimensional", nsURI: "urn:schemas-microsoft-com:xml-analysis:rowset:multidimensional", optional: false },
  { name: "rowset-mining-restrictions", nsURI: "https://www.daanse.org/spec/xmla/rowset/mining/restrictions/1.0", optional: false },
  { name: "rowset-mining", nsURI: "urn:schemas-microsoft-com:xml-analysis:rowset:mining", optional: false },
  { name: "rowset-server-restrictions", nsURI: "https://www.daanse.org/spec/xmla/rowset/server/restrictions/1.0", optional: false },
  { name: "rowset-server", nsURI: "urn:schemas-microsoft-com:xml-analysis:rowset:server", optional: false },
  { name: "rowset-tabular-restrictions", nsURI: "https://www.daanse.org/spec/xmla/rowset/tabular/restrictions/1.0", optional: false },
  { name: "rowset-tabular", nsURI: "urn:schemas-microsoft-com:xml-analysis:rowset:tabular", optional: false },
  { name: "soap", nsURI: "http://schemas.xmlsoap.org/soap/envelope/", optional: false },
  { name: "xmla", nsURI: "urn:schemas-microsoft-com:xml-analysis", optional: false },
];
