/*
 * Copyright (c) 2026 Contributors to the Eclipse Foundation.
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 */

/**
 * Copies the Ecore models listed in model-sources.json into xmla-model.
 *
 * Beyond copying, this checks the two things about the model set that the
 * loader relies on and that nothing else would notice going wrong: that the
 * declared nsURI still matches what the file actually says, and that the
 * declared order really is topological. Both are cheap here and expensive to
 * debug later, when a type silently fails to resolve.
 *
 *   node scripts/sync-ecore.mjs [--check]
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

import { readSources, repoRoot, syncFiles } from './sync-lib.mjs';

const check = process.argv.includes('--check');
const sources = readSources();
const targetDir = join(repoRoot, 'packages', 'xmla-model', 'model');

const entries = sources.models.map((model) => ({
  from: join(sources.sourceRoot, model.file),
  to: `${model.name}.ecore`,
}));

const problems = syncFiles({
  label: 'ecore',
  sourceRoot: sources.sourceRoot,
  targetDir,
  manifestName: '_manifest.json',
  entries,
  check,
});

// Only worth asking once the copies are known good. Verifying the source after a
// copy already failed would print a reassuring line underneath the failure.
if (problems > 0) {
  process.exit(1);
}

const declarationProblems = verifyDeclarations(sources, targetDir);
if (declarationProblems > 0) {
  process.exit(1);
}

process.exit(syncModelOrder(sources, check) === 0 ? 0 : 1);

/**
 * Writes the load order into the package as TypeScript.
 *
 * model-sources.json sits at the repository root and is not published, but the
 * order is not optional information: cross-model types resolve through the
 * registry by nsURI, so a model has to be registered before whatever uses it is
 * read. Generating it keeps the two from drifting.
 */
function syncModelOrder(sources, check) {
  const entries = sources.models
    .map(
      (model) =>
        `  { name: ${JSON.stringify(model.name)}, nsURI: ${JSON.stringify(model.nsURI)}, optional: ${model.optional === true} },`,
    )
    .join('\n');

  const generated = `/*
 * Copyright (c) 2026 Contributors to the Eclipse Foundation.
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 */

/**
 * Generated by scripts/sync-ecore.mjs from model-sources.json - do not edit.
 *
 * Topological: every model appears after the ones it references. An \`optional\`
 * model is left out unless asked for; today that is only \`engine\`, 868 KB whose
 * absence costs exactly 18 features, all on DDL commands a client never sends.
 */
export interface ModelDescriptor {
  readonly name: string;
  readonly nsURI: string;
  readonly optional: boolean;
}

export const MODEL_ORDER: readonly ModelDescriptor[] = [
${entries}
];
`;

  const path = join(repoRoot, 'packages', 'xmla-model', 'src', 'models.generated.ts');
  const current = existsSync(path) ? readFileSync(path, 'utf8') : null;

  if (check) {
    if (current !== generated) {
      console.error('ecore: models.generated.ts is out of step with model-sources.json');
      console.error("Run 'npm run sync:ecore' to regenerate it.");
      return 1;
    }
    console.log(`ecore: models.generated.ts matches (${sources.models.length} models)`);
    return 0;
  }

  if (current !== generated) {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, generated);
  }
  console.log(`ecore: models.generated.ts written (${sources.models.length} models)`);
  return 0;
}

/**
 * The nsURI in model-sources.json is what the loader registers a package under.
 * If the file ever declares something else, every cross-model type reference
 * into it turns into an unresolved proxy - and a proxy reads as an empty value
 * rather than as an error.
 */
function verifyDeclarations(sources, dir) {
  const found = [];
  const seen = new Set();

  for (const model of sources.models) {
    const path = join(dir, `${model.name}.ecore`);
    let text;
    try {
      text = readFileSync(path, 'utf8');
    } catch {
      found.push(`cannot read ${model.name}`);
      continue;
    }

    const declared = /nsURI="([^"]*)"/.exec(text);
    if (declared === null) {
      found.push(`${model.name}: the file declares no nsURI`);
    } else if (declared[1] !== model.nsURI) {
      found.push(`${model.name}: declares ${declared[1]}, model-sources.json says ${model.nsURI}`);
    }

    for (const dependency of model.dependsOn) {
      if (!seen.has(dependency)) {
        found.push(`${model.name} depends on ${dependency}, which is not loaded before it`);
      }
    }
    seen.add(model.nsURI);
  }

  if (found.length > 0) {
    console.error(`ecore: ${found.length} declaration problem(s)`);
    for (const problem of found) {
      console.error(`  - ${problem}`);
    }
    return found.length;
  }
  console.log(`ecore: ${sources.models.length} nsURI(s) declared as expected, order is topological`);
  return 0;
}
