/*
 * Copyright (c) 2026 Contributors to the Eclipse Foundation.
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 */
import { anEcore } from './an.generated.js';
import { biEcore } from './bi.generated.js';
import { cgEcore } from './cg.generated.js';
import { edmEcore } from './edm.generated.js';
import { emptyEcore } from './empty.generated.js';
import { engine300Ecore } from './engine300.generated.js';
import { engine300300Ecore } from './engine300_300.generated.js';
import { engineEcore } from './engine.generated.js';
import { engine200Ecore } from './engine200.generated.js';
import { engine200200Ecore } from './engine200_200.generated.js';
import { exceptionEcore } from './exception.generated.js';
import { extEcore } from './ext.generated.js';
import { mddatasetEcore } from './mddataset.generated.js';
import { msxmlaEcore } from './msxmla.generated.js';
import { multipleresultsEcore } from './multipleresults.generated.js';
import { rowsetCoreEcore } from './rowset-core.generated.js';
import { rowsetCoreRestrictionsEcore } from './rowset-core-restrictions.generated.js';
import { rowsetRelationalRestrictionsEcore } from './rowset-relational-restrictions.generated.js';
import { rowsetRelationalEcore } from './rowset-relational.generated.js';
import { rowsetMultidimensionalRestrictionsEcore } from './rowset-multidimensional-restrictions.generated.js';
import { rowsetMultidimensionalEcore } from './rowset-multidimensional.generated.js';
import { rowsetMiningRestrictionsEcore } from './rowset-mining-restrictions.generated.js';
import { rowsetMiningEcore } from './rowset-mining.generated.js';
import { rowsetServerRestrictionsEcore } from './rowset-server-restrictions.generated.js';
import { rowsetServerEcore } from './rowset-server.generated.js';
import { rowsetTabularRestrictionsEcore } from './rowset-tabular-restrictions.generated.js';
import { rowsetTabularEcore } from './rowset-tabular.generated.js';
import { soapEcore } from './soap.generated.js';
import { xmlaEcore } from './xmla.generated.js';

/**
 * Generated by scripts/sync-ecore.mjs - do not edit.
 *
 * Every model as text, keyed by name, so a browser can bootstrap without a
 * filesystem. `npm run check:sync` fails when these drift from the .ecore.
 */
export const MODEL_TEXT: Readonly<Record<string, string>> = {
  "an": anEcore,
  "bi": biEcore,
  "cg": cgEcore,
  "edm": edmEcore,
  "empty": emptyEcore,
  "engine300": engine300Ecore,
  "engine300_300": engine300300Ecore,
  "engine": engineEcore,
  "engine200": engine200Ecore,
  "engine200_200": engine200200Ecore,
  "exception": exceptionEcore,
  "ext": extEcore,
  "mddataset": mddatasetEcore,
  "msxmla": msxmlaEcore,
  "multipleresults": multipleresultsEcore,
  "rowset-core": rowsetCoreEcore,
  "rowset-core-restrictions": rowsetCoreRestrictionsEcore,
  "rowset-relational-restrictions": rowsetRelationalRestrictionsEcore,
  "rowset-relational": rowsetRelationalEcore,
  "rowset-multidimensional-restrictions": rowsetMultidimensionalRestrictionsEcore,
  "rowset-multidimensional": rowsetMultidimensionalEcore,
  "rowset-mining-restrictions": rowsetMiningRestrictionsEcore,
  "rowset-mining": rowsetMiningEcore,
  "rowset-server-restrictions": rowsetServerRestrictionsEcore,
  "rowset-server": rowsetServerEcore,
  "rowset-tabular-restrictions": rowsetTabularRestrictionsEcore,
  "rowset-tabular": rowsetTabularEcore,
  "soap": soapEcore,
  "xmla": xmlaEcore,
};
